# Generated by Django 3.2.4 on 2021-06-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
    ]
